from __future__ import annotations

import math
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

from datasets.torch_dataset import WifallDataset
from training.model import FallDetector


def build_datasets(cfg: dict) -> tuple[WifallDataset, WifallDataset]:
    """Split manifest by target_subject for subject-out evaluation.

    Returns (train_dataset, test_dataset).
    train = all subjects except target_subject
    test  = target_subject only

    Source-of-truth for target_subject (checked in this order):
      1. data.split_yaml_path — path to configs/splits/wifall_subject_split.yaml
         generated by scripts/prepare_wifall.py.  Preferred: editing
         configs/dataset.yaml and re-running prepare_wifall.py is the single
         way to change the split.
      2. data.target_subject — inline fallback for tests / ad-hoc runs.
    """
    import pandas as pd
    import yaml as _yaml

    data_cfg = cfg["data"]
    manifest_path = data_cfg["manifest_path"]
    zip_path = data_cfg["zip_path"]

    split_yaml_path = data_cfg.get("split_yaml_path")
    if split_yaml_path:
        with open(split_yaml_path, encoding="utf-8") as _f:
            _split = _yaml.safe_load(_f)
        target_subject = _split["target_subject"]
    else:
        target_subject = data_cfg["target_subject"]

    manifest = pd.read_csv(manifest_path)
    all_subjects = manifest["subject_id"].unique().tolist()
    train_subjects = [s for s in all_subjects if s != target_subject]
    test_subjects = [target_subject]

    train_dataset = WifallDataset(
        manifest_path=manifest_path,
        zip_path=zip_path,
        subjects=train_subjects,
    )
    test_dataset = WifallDataset(
        manifest_path=manifest_path,
        zip_path=zip_path,
        subjects=test_subjects,
    )
    return train_dataset, test_dataset


def _compute_pos_weight(dataset: WifallDataset) -> torch.Tensor:
    """Compute pos_weight for BCEWithLogitsLoss from dataset labels."""
    labels = [dataset[i][1] for i in range(len(dataset))]
    n_pos = sum(labels)
    n_neg = len(labels) - n_pos
    if n_pos == 0:
        return torch.tensor(1.0)
    return torch.tensor(n_neg / n_pos, dtype=torch.float32)


def train(cfg: dict) -> dict:
    """Full training loop. Returns metrics dict.

    - Uses BCEWithLogitsLoss (model outputs raw logits)
    - AdamW optimizer, lr from cfg
    - Prints epoch loss every epoch
    - Returns {"train_loss_history": [...], "best_epoch": int}
    """
    training_cfg = cfg["training"]
    model_cfg = cfg.get("model", {})

    batch_size = training_cfg.get("batch_size", 64)
    epochs = training_cfg.get("epochs", 40)
    lr = training_cfg.get("learning_rate", 0.0005)
    n_subcarriers = cfg["data"].get("n_subcarriers", 52)

    device = torch.device("cpu")

    train_dataset, _ = build_datasets(cfg)

    pos_weight = _compute_pos_weight(train_dataset)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    model = FallDetector(
        n_subcarriers=n_subcarriers,
        conv_channels=model_cfg.get("conv_channels", [64, 128, 128]),
        kernel_sizes=model_cfg.get("kernel_sizes", [5, 3, 3]),
        dropout=model_cfg.get("dropout", 0.5),
    ).to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)

    train_loss_history = []
    best_loss = float("inf")
    best_epoch = 0
    restart_attempted = False

    for epoch in range(1, epochs + 1):
        model.train()
        epoch_loss = 0.0
        n_batches = 0

        for x_batch, y_batch in train_loader:
            x_batch = x_batch.to(device)
            y_batch = y_batch.float().unsqueeze(1).to(device)

            optimizer.zero_grad()
            logits = model(x_batch)
            loss = criterion(logits, y_batch)

            if math.isnan(loss.item()):
                # Loss diverged — halve lr and restart (once)
                if not restart_attempted:
                    print(f"  [WARN] NaN loss at epoch {epoch}. Halving lr and restarting.")
                    restart_attempted = True
                    lr = lr / 2
                    for param_group in optimizer.param_groups:
                        param_group["lr"] = lr
                    # Re-init model weights
                    for layer in model.modules():
                        if hasattr(layer, "reset_parameters"):
                            layer.reset_parameters()
                    epoch_loss = float("nan")
                    break
                else:
                    print(f"  [ERROR] NaN loss persists after lr reduction. Stopping training.")
                    train_loss_history.append(float("nan"))
                    return {
                        "train_loss_history": train_loss_history,
                        "best_epoch": best_epoch,
                        "model": model,
                    }

            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
            n_batches += 1

        if math.isnan(epoch_loss):
            # Restart this epoch index after nan recovery
            epoch_loss = 0.0
            continue

        avg_loss = epoch_loss / max(n_batches, 1)
        train_loss_history.append(avg_loss)
        print(f"Epoch [{epoch:3d}/{epochs}]  loss={avg_loss:.4f}")

        if avg_loss < best_loss:
            best_loss = avg_loss
            best_epoch = epoch

    return {
        "train_loss_history": train_loss_history,
        "best_epoch": best_epoch,
        "model": model,
    }


def evaluate(model: FallDetector, dataset: WifallDataset, cfg: dict) -> dict:
    """Evaluate on a dataset. Returns metrics dict.

    - Apply sigmoid to logits to get probabilities
    - Apply threshold to get hard labels
    - Returns: accuracy, precision, recall, f1, confusion_matrix (2x2 list),
               raw predictions list
    """
    training_cfg = cfg["training"]
    threshold = training_cfg.get("threshold", 0.5)
    batch_size = training_cfg.get("batch_size", 64)

    device = torch.device("cpu")
    model = model.to(device)
    model.eval()

    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)

    all_probs: list[float] = []
    all_preds: list[int] = []
    all_labels: list[int] = []

    with torch.no_grad():
        for x_batch, y_batch in loader:
            x_batch = x_batch.to(device)
            logits = model(x_batch)
            probs = torch.sigmoid(logits).squeeze(1).cpu().tolist()
            if isinstance(probs, float):
                probs = [probs]
            labels = y_batch.tolist()
            if isinstance(labels, int):
                labels = [labels]
            preds = [1 if p >= threshold else 0 for p in probs]
            all_probs.extend(probs)
            all_preds.extend(preds)
            all_labels.extend(labels)

    # Confusion matrix: [[TN, FP], [FN, TP]]
    tn = fp = fn = tp = 0
    for true, pred in zip(all_labels, all_preds):
        if true == 0 and pred == 0:
            tn += 1
        elif true == 0 and pred == 1:
            fp += 1
        elif true == 1 and pred == 0:
            fn += 1
        elif true == 1 and pred == 1:
            tp += 1

    total = len(all_labels)
    accuracy = (tp + tn) / total if total > 0 else 0.0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0

    # Build per-window predictions
    raw_predictions = []
    for i in range(len(dataset)):
        row = dataset._rows[i] if hasattr(dataset, "_rows") else {}
        raw_predictions.append({
            "source_file": row.get("source_file", ""),
            "window_index": row.get("window_index", i),
            "true_label": all_labels[i],
            "pred_prob": all_probs[i],
            "pred_label": all_preds[i],
        })

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "confusion_matrix": [[tn, fp], [fn, tp]],
        "raw_predictions": raw_predictions,
        # Raw scores — available for threshold sweep and curve generation
        # without re-running inference.
        "all_probs": all_probs,
        "all_labels": all_labels,
    }
